import React from "react";
import { jsPDF } from "jspdf";

export default function ExportReport({ audit }) {
  const handleExport = () => {
    const doc = new jsPDF();

    // Title
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("Smart Contract Security Audit Report", 20, 20);

    // Metadata
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 28);

    // Separator line
    doc.setDrawColor(200);
    doc.line(20, 32, 190, 32);

    // Security Grade Box
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0);
    doc.text("Security Assessment", 20, 42);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(`Security Grade: ${audit.security_grade || "N/A"}`, 20, 50);
    doc.text(
      `CVSS Score: ${audit.cvss_score?.toFixed(1) || "N/A"}/10.0`,
      20,
      57
    );

    // Contract Details
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Contract Details", 20, 70);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Contract Hash:", 20, 78);
    doc.setFont("courier", "normal");
    doc.text(audit.contract_hash || "N/A", 20, 84);
    doc.setFont("helvetica", "normal");
    doc.text("Transaction Hash:", 20, 92);
    doc.setFont("courier", "normal");
    doc.text(audit.tx_hash || "N/A", 20, 98);
    doc.setFont("helvetica", "normal");
    doc.text("IPFS CID:", 20, 106);
    doc.setFont("courier", "normal");
    doc.text(audit.cid || "N/A", 20, 112);

    // Summary
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Security Summary", 20, 125);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    const summaryLines = doc.splitTextToSize(audit.summary || "No summary available", 170);
    doc.text(summaryLines.slice(0, 30), 20, 133); // Limit to ~30 lines

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by Smart Audit Platform", 20, pageHeight - 10);
    doc.text(
      "This report is for informational purposes only and does not guarantee contract security.",
      20,
      pageHeight - 6
    );

    // Save PDF
    const filename = `audit_${audit.contract_hash?.slice(0, 8) || "unknown"}_${Date.now()}.pdf`;
    doc.save(filename);
  };

  return (
    <button
      onClick={handleExport}
      className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-md mt-4 transition"
    >
      📄 Export Report as PDF
    </button>
  );
}
